"""
Datagateway — Taxonomy (CODE)
Canonical SECTION_KEYWORDS definitions. Single source of truth.

Merged from: enrich-metadata.py (primary) + auto-meta.py (secondary supplement).
"""

SECTION_KEYWORDS: dict[str, list[str]] = {
    "POLITIK": [
        # from enrich-metadata.py
        "presiden", "presiden prabowo", "pemerintah", "dpr", "dprd",
        "menteri", "kabinet", "partai", "politik", "pemilu", "pilkada",
        "koalisi", "oposisi", "voting", "sidang", "undang-undang", "uu",
        "peraturan pemerintah", "pp", "presidential", "executive", "legislative",
        "governor", "walikota", "bupati", "kemente", "raiban", "kpk",
        "hak angket", "interpelasi", "mosi tidak percaya", "impeachment",
        "mpr", "dpd", "mk", "ky", "mahkamah", "hak", "uu cipta kerja",
        "omnibus", "revisi", "tnic", "pencalonan", "kandidat",
        # from auto-meta.py supplement
        "jokowi", "gubernur", "fraksi", "konstitusi", "amendemen",
        "demo", "unjuk rasa", "kebijakan", "anggaran",
    ],
    "EKONOMI": [
        "ekonomi", "saham", "idx", "idx80", "inflasi", "rupiah", "dollar", "usd",
        "bank", "bjb", "bni", "bri", "btn", "mandiri", "bi rate", "suku bunga",
        "odb", "ocr", "g20", "freeport", "neraca perdagangan", "ekspor", "impor",
        "cadangan devisa", "dbnc", "pemda", "apbd", "apbn", "belanja negara",
        "pajak", "ppn", "pph", "pttp", "penerimaan negara", "defisit",
        "investor", "investasi", "green bond", "sbn", "obligasi", "surat utang",
        "kredit", "kpr", "kmm", "umkm", "kmnp", "korporasi", "indu", "industri",
        "pertambangan", "batubara", "emas", "n kel", "agr", "migas", "cpo",
        "kakao", "kopi", "sawit", "property", "real estat",
        "pt unilever", "unilever", "adaro", "sinar mas", "sampoerna", "gudang garam",
        "bumn", "swasta", "fta", "wto", "bpom", "food", "minuman", "farmasi",
        "phs", "ksehatan", "textil", "aviation", "pariwisata", "transportasi",
        "logistik", "startup", "unicorn", "decacorn", "fintech", "crypto", "bitcoin",
        "blk", "lps", "ock", "freeport", "newmont", "antam", "timah",
        # from auto-meta.py supplement
        "dolar", "pasar modal", "biz", "bisnis", "utang",
        "valas", "sukuk", "reksadana", "finansial",
        "asuransi", "pinjaman", "likuiditas",
        "lab bersih", "pendapatan", "omzet", "produsen", "konsumen",
    ],
    "TEKNOLOGI": [
        "teknologi", "digital", "internet", "software", "hardware", "ai",
        "kecerdasan buatan", "otomatisasi", "robot", "cyber", "siber",
        "data", "cloud", "server", "startup", "unicorn", "app", "aplikasi",
        "platform", "e-commerce", "e-", "iot", "5g", "6g", "semiconductor",
        "chip", "processor", "nvidia", "amd", "intel", "apple", "google", "meta",
        "microsoft", "amazon", "tesla", "spacex", "openai", "chatgpt", "llm",
        "gensim", "transformer", "langchain", "big data", "analytics",
        "cybersecurity", "ransomware", "malware", "phishing", "hack", "breach",
        "developer", "programming", "python", "javascript", "java", "golang",
        "api", "sdk", "saas", "paas", "iaas", "devops", "agile",
        # from auto-meta.py supplement
        "semikonduktor", "blockchain", "kripto",
    ],
    "OLAHRAGA": [
        "olahraga", "sepak bola", "bola", "basket", "voli", "renang",
        "atlet", "pial", "world cup", "cup", "liga", "champions", "premier",
        "serie", "la liga", "bundesliga", "league", "turnamen", "olimpiade",
        "sea games", "asi games", "asiad", "aff", "piala", "final",
        "gol", "score", "skor", "hasil", "pertandingan", "tim", "timnas",
        "indonesia", "persib", "persija", "arema", "pss", "psm", "persebaya",
        "bola dunia", "fifa", "pssi", "wasit", "offside", "var",
        "ferrari", "mclaren", "mercedes", "f1", "motogp", "tenis", "badminton",
        "bwf", "all england", "krl", "pb djarum", "jakarta", "surabaya",
    ],
    "HUKUM": [
        "hukum", "pidana", "perdata", "tata negara", "kasasi", "pk", "peninjauan kembali",
        "putusan", "vonis", "tuntutan", "dakwaan", "terdakwa", "tersangka",
        "terpidana", "narapidana", "napi", "lapas", "lembaga pemasyarakatan",
        "kejaksaan", "jaksa", "polisi", "polri", "kepolisian",
        "penyidikan", "penyelidikan", "sidak", "razia", "tangkap",
        "tahanan", "penahanan", "bui", "penjara", "hukuman",
        "kekerasan", "penganiayaan", "pembunuhan", "korupsi", "tipikor",
        "pencucian uang", "tppu", "kpk", "kpk", "ojk", "ppatk",
    ],
    "INTERNASIONAL": [
        "internasional", "dunia", "global", "as", "amerika", "china", "tiongkok",
        "russia", "rusia", "inggris", "uk", "united kingdom", "jerman",
        "prancis", "jepang", "korea", "india", "australia",
        "pbb", "un", "unicef", "who", "imf", "world bank", "nato",
        "uni eropa", "eu", "asean", "g20", "g7", "g8",
        "konflik", "perang", "invasi", "sanksi", "diplomatic",
        "luar negeri", "menlu", "kedutaan", "dubes",
        "palestina", "israel", "ukraina", "iran", "arab",
        "venezuela", "kuba", "suriah", "afghan",
    ],
    "KESEHATAN": [
        "kesehatan", "rumah sakit", "rs", "puskesmas", "dokter", "perawat",
        "obat", "vaksin", "imunisasi", "penyakit", "virus", "bakteri",
        "pandemi", "epidemi", "endemi", "covid", "corona", "sars",
        "rumah sakit", "rsud", "bpjs", "jaminan kesehatan",
        "gizi", "stunting", "malnutrisi", "imt", "obesitas",
        "operasi", "transplantasi", "kanker", "tumor", "stroke",
        "jantung", "diabetes", "hipertensi", "mental",
        "rs jiwa", "narkoba", "napza", "rehabilitasi",
    ],
    "PENDIDIKAN": [
        "pendidikan", "sekolah", "sd", "smp", "sma", "smk", "madrasah",
        "universitas", "univ", "institut", "kampus", "mahasisw",
        "dosen", "guru", "murid", "siswa", "peserta didik",
        "ujian", "un", "skripsi", "tesis", "disertasi",
        "beasiswa", "lpdp", "kemdikbud", "kemendikbud",
        "kurikulum", "merdeka belajar", "pppk", "cpns",
        "pesantren", "madrasah", "boarding school",
    ],
    "LINGKUNGAN": [
        "lingkungan", "alam", "hutan", "laut", "sungai", "danau",
        "polusi", "pencemaran", "limbah", "sampah", "plastik",
        "iklim", "perubahan iklim", "climate change", "global warming",
        "pemanasan global", "emisi", "karbon", "net zero",
        "bencana", "gempa", "tsunami", "banjir", "longsor",
        "gunung", "meletus", "erupsi", "letusan",
        "kekeringan", "cuaca ekstrem", "angin", "topan",
        "bmkg", "bnpb", "mitigasi", "tanggap darurat",
    ],
    "BUDAYA": [
        "budaya", "seni", "musik", "film", "drama", "teater",
        "pameran", "konser", "festival", "pagelaran",
        "tarian", "tari", "lukis", "patung", "sastra",
        "novel", "puisi", "cerpen", "komik", "manga",
        "kpop", "drakor", "drama korea", "jpop", "anime",
        "sejarah", "cagar budaya", "warisan", "heritage",
        "tradisi", "adat", "upacara", "ritual",
        "tokoh", "budayawan", "seniman", "pelukis",
    ],
}

SECTION_ALIASES: dict[str, list[str]] = {
    "POLITIK": ["pemerintahan", "kebijakan publik", "administrasi negara"],
    "EKONOMI": ["bisnis", "keuangan", "finansial", "perdagangan"],
    "TEKNOLOGI": ["sains", "riset", "iptek", "inovasi"],
    "OLAHRAGA": ["sport", "sports", "pertandingan"],
    "HUKUM": ["kriminal", "kriminalitas", "yustisi"],
    "INTERNASIONAL": ["mancanegara", "hubungan internasional", "luar negeri"],
    "KESEHATAN": ["medis", "klinis", "farmasi"],
    "PENDIDIKAN": ["akademik", "belajar", "pengajaran"],
    "LINGKUNGAN": ["ekologi", "konservasi", "bencana alam"],
    "BUDAYA": ["hiburan", "entertainment", "kesenian", "kreatif"],
}
